### ISSUE TITLE
Incorrect example imports 

### ISSUE THREAD

**Issue by LaineZ** [AregevDev/rustcord#3]
Incorrect imports in example
```error[E0432]: unresolved import `discord_rpc`
 --> src\lib.rs:4:5
  |
4 | use discord_rpc::{DiscordRPC, EventHandlers, RichPresenceBuilder, User};
  |     ^^^^^^^^^^^ use of undeclared type or module `discord_rpc```

**Comment by AregevDev** [comment]
I have to update those, will be fixed

**Comment by AregevDev** [comment]
@LaineZ This should be fixed now, please update `rustcord` to 0.2.4, tell me if it does not

**Comment by LaineZ** [comment]
sorry for long delay - now all works good. thanks
